### ISSUE TITLE
brainblocks is not published on pypi

### ISSUE THREAD

**Issue by HMaker** [the-aerospace-corporation/brainblocks#12]
I searched for "brainblocks" on [pypi](https://pypi.org/search/?q=brainblocks) but found nothing. It would be good to publish it on pypi so dependency confusion attacks can be avoided. This [requirements file][1] on image classification experiments folder refer to "brainblocks" without any location, so pip will search it on pypi, If there is some malicious package named "brainblocks" there it will be installed.

[1]: https://github.com/the-aerospace-corporation/brainblocks/blob/9d1e210c0a6512704ef005aae8228c45016b2f5f/examples/python/experiments/image_classification/requirements.txt

**Comment by jacobeverist** [comment]
Thanks for the notification.  This has been on our todo list.  The trick is to build a platform-specific version of each of the operating systems since it has a shared library built from C++.  If it was just python code, then this would be much more straight forward.

Also, I haven't quite learned how to package and publish to pypi yet, so that's also that needs to be done.  You want to volunteer?

**Comment by jacobeverist** [comment]
Fixed and published for v0.7.1
